# Generated by Django 5.0.2 on 2024-02-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yournews', '0003_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
