# Generated by Django 5.0.2 on 2024-03-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yournews', '0004_rename_create_at_news_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
