# Generated by Django 5.0.2 on 2024-03-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yournews', '0007_profile_facebook_link_profile_homepage_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='homepage_link',
            new_name='website_link',
        ),
    ]
