# Generated by Django 5.0.2 on 2024-03-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yournews', '0008_rename_homepage_link_profile_website_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
