# Generated by Django 5.0.2 on 2024-03-19 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yournews', '0011_remove_comment_commenter_remove_comment_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
