# Generated by Django 5.0.2 on 2024-03-19 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yournews', '0013_comment_post_alter_comment_commenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='yournews.news'),
            preserve_default=False,
        ),
    ]
