# Generated by Django 5.0.2 on 2024-03-19 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yournews', '0016_alter_comment_commenter_alter_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comment_body',
        ),
    ]
