# Generated by Django 4.2.7 on 2024-03-20 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yournews', '0017_rename_comment_comment_comment_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='news',
        ),
    ]
