# Generated by Django 4.2.7 on 2024-03-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yournews', '0018_rename_post_comment_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
